"""APM Python SDK — Synology ActiveProtect Manager Python SDK."""
from importlib.metadata import version as _get_version

from .client import APMClient
from .collections._shared import ListResult
from .collections.activities import ActivityCollection, BackupActivityCollection, RestoreActivityCollection
from .collections.backup_servers import BackupServerCollection
from .collections.hypervisors import HypervisorCollection
from .collections.logs import LogCollection
from .collections.m365 import M365Collection, M365WorkloadCollection
from .collections.m365_auto_backup_rule import M365AutoBackupRuleCollection
from .collections.m365_mail_export import (
    ExchangeExportCollection,
    GroupExportCollection,
    M365ExportStartResult,
)
from .collections.machine import MachineCollection, MachineWorkloadCollection
from .collections.protection_plans import M365PlanCollection, MachinePlanCollection, ProtectionPlanCollection
from .collections.remote_storages import RemoteStorageCollection
from .collections.retirement_plans import RetirementPlanCollection
from .collections.saas import SaasCollection
from .collections.tiering_plans import TieringPlanCollection
from .config import (
    CONFIG_FILE,
    DEFAULT_PROFILE,
    AppConfig,
    PasswordStorage,
    ProfileConfig,
    ResolvedConnection,
    delete_keyring_password,
    load_config,
    resolve_connection,
    save_config,
    set_keyring_password,
)
from .enums import (
    ActivityWorkloadType,
    APMActivityLogType,
    BackupActivityStatus,
    BackupScope,
    BackupServerRole,
    BackupServerType,
    CopyReason,
    DbActionOnError,
    FileServerType,
    HypervisorType,
    LogLevel,
    M365ExportStatus,
    M365WorkloadType,
    MachineOsType,
    MachineTaskScope,
    MachineWorkloadType,
    MssqlLogSetting,
    OracleLogSetting,
    RemoteStorageStatus,
    RemoteStorageType,
    RestoreActivityStatus,
    RestoreType,
    RetentionType,
    ScheduleFrequency,
    ServerStatus,
    VerifyStatus,
    VersionCopyStatus,
    VersionStatus,
    WeekDay,
    WorkloadCategory,
    WorkloadStatType,
    WorkloadStatus,
)
from .exceptions import (
    ERROR_CODES,
    APIError,
    APMError,
    AuthenticationError,
    BackupServerDisconnectedError,
    ConnectionTimeoutError,
    DuplicateWorkloadError,
    InvalidOperationError,
    KeyringUnavailableError,
    NotManagementServerError,
    NotSupportedError,
    PermissionDeniedError,
    PlanInUseError,
    PlanNameConflictError,
    RemoteStorageConflictError,
    RemoteStorageEncryptionMismatchError,
    RemoteStorageInUseError,
    RemoteStorageUnmanagedCatalogError,
    ResourceNotFoundError,
    ResourceNotReadyError,
    classify_error,
)
from .models.activity import Activity, ActivityLogEntry, BackupActivity, M365ExportActivity, RestoreActivity
from .models.backup_server import BackupServer
from .models.hypervisor import Hypervisor
from .models.location import LocationInfo
from .models.log import APMActivityLog, ConnectionLog, DriveLog, SystemLog
from .models.m365_auto_backup_rule import M365AutoBackupRule, M365AutoBackupRuleListResult, M365CollabServiceSetting
from .models.protection_plan import (
    BackupCopyConfig,
    BackupCopyPolicy,
    EventTriggerConfig,
    GFSRetention,
    M365PlanCreateRequest,
    MachineBackupWindow,
    MachineDbConfig,
    MachinePcConfig,
    MachinePlanCreateRequest,
    MachinePsConfig,
    MachineTaskConfig,
    MachineTaskSchedule,
    MachineVmConfig,
    PlanBackupCopyStatus,
    ProtectionPlan,
    ProtectionPlanPolicy,
    ProtectionRetentionPolicy,
    ProtectionSchedule,
)
from .models.remote_storage import (
    AmazonS3ChinaStorageAddRequest,
    AmazonS3StorageAddRequest,
    APVStorageAddRequest,
    C2ObjectStorageAddRequest,
    GenericS3StorageAddRequest,
    RemoteStorage,
    RemoteStorageAddResult,
    RemoteStorageUpdateRequest,
    WasabiCloudStorageAddRequest,
)
from .models.retirement_plan import RetirementPlan, RetirementPlanCreateRequest, RetirementRetentionPolicy
from .models.saas import SaasTenant
from .models.system import SiteInfo, SiteStorageStats, WorkloadTypeStat, WorkloadUsageSummary
from .models.tiering_plan import TieringPlan, TieringPlanCreateRequest, TieringStatus
from .models.version import VersionLocation, WorkloadVersion
from .models.workload import (
    FileServerAddRequest,
    FileServerConfig,
    FileServerPathSelector,
    FileServerUpdateRequest,
    M365GroupInfo,
    M365Info,
    M365SiteInfo,
    M365TeamInfo,
    M365UserInfo,
    M365Workload,
    MachineWorkload,
    Workload,
)

__version__ = _get_version("synology-apm-sdk")
__all__ = [
    "APIError",
    "APMActivityLog",
    "APMActivityLogType",
    "APMClient",
    "APMError",
    "APVStorageAddRequest",
    "Activity",
    "ActivityCollection",
    "ActivityLogEntry",
    "ActivityWorkloadType",
    "AmazonS3ChinaStorageAddRequest",
    "AmazonS3StorageAddRequest",
    "AppConfig",
    "AuthenticationError",
    "BackupActivity",
    "BackupActivityCollection",
    "BackupActivityStatus",
    "BackupCopyConfig",
    "BackupCopyPolicy",
    "BackupScope",
    "BackupServer",
    "BackupServerCollection",
    "BackupServerDisconnectedError",
    "BackupServerRole",
    "BackupServerType",
    "C2ObjectStorageAddRequest",
    "classify_error",
    "CONFIG_FILE",
    "ConnectionLog",
    "ConnectionTimeoutError",
    "CopyReason",
    "DbActionOnError",
    "DEFAULT_PROFILE",
    "delete_keyring_password",
    "DriveLog",
    "DuplicateWorkloadError",
    "ERROR_CODES",
    "EventTriggerConfig",
    "ExchangeExportCollection",
    "FileServerAddRequest",
    "FileServerConfig",
    "FileServerPathSelector",
    "FileServerType",
    "FileServerUpdateRequest",
    "GFSRetention",
    "GenericS3StorageAddRequest",
    "GroupExportCollection",
    "Hypervisor",
    "HypervisorCollection",
    "HypervisorType",
    "InvalidOperationError",
    "KeyringUnavailableError",
    "load_config",
    "ListResult",
    "LocationInfo",
    "LogCollection",
    "LogLevel",
    "M365AutoBackupRule",
    "M365AutoBackupRuleCollection",
    "M365AutoBackupRuleListResult",
    "M365CollabServiceSetting",
    "M365Collection",
    "M365ExportActivity",
    "M365ExportStartResult",
    "M365ExportStatus",
    "M365GroupInfo",
    "M365Info",
    "M365PlanCollection",
    "M365PlanCreateRequest",
    "M365SiteInfo",
    "M365TeamInfo",
    "M365UserInfo",
    "M365Workload",
    "M365WorkloadCollection",
    "M365WorkloadType",
    "MachineBackupWindow",
    "MachineCollection",
    "MachineDbConfig",
    "MachineOsType",
    "MachinePcConfig",
    "MachinePlanCollection",
    "MachinePlanCreateRequest",
    "MachinePsConfig",
    "MachineTaskConfig",
    "MachineTaskSchedule",
    "MachineTaskScope",
    "MachineVmConfig",
    "MachineWorkload",
    "MachineWorkloadCollection",
    "MachineWorkloadType",
    "MssqlLogSetting",
    "NotManagementServerError",
    "NotSupportedError",
    "OracleLogSetting",
    "PasswordStorage",
    "PermissionDeniedError",
    "PlanBackupCopyStatus",
    "PlanInUseError",
    "PlanNameConflictError",
    "ProfileConfig",
    "ProtectionPlan",
    "ProtectionPlanCollection",
    "ProtectionPlanPolicy",
    "ProtectionRetentionPolicy",
    "ProtectionSchedule",
    "RemoteStorage",
    "RemoteStorageAddResult",
    "RemoteStorageCollection",
    "RemoteStorageConflictError",
    "RemoteStorageEncryptionMismatchError",
    "RemoteStorageInUseError",
    "RemoteStorageStatus",
    "RemoteStorageType",
    "RemoteStorageUnmanagedCatalogError",
    "RemoteStorageUpdateRequest",
    "resolve_connection",
    "ResolvedConnection",
    "ResourceNotFoundError",
    "ResourceNotReadyError",
    "RestoreActivity",
    "RestoreActivityCollection",
    "RestoreActivityStatus",
    "RestoreType",
    "RetentionType",
    "RetirementPlan",
    "RetirementPlanCollection",
    "RetirementPlanCreateRequest",
    "RetirementRetentionPolicy",
    "SaasCollection",
    "SaasTenant",
    "save_config",
    "ScheduleFrequency",
    "ServerStatus",
    "set_keyring_password",
    "SiteInfo",
    "SiteStorageStats",
    "SystemLog",
    "TieringPlan",
    "TieringPlanCollection",
    "TieringPlanCreateRequest",
    "TieringStatus",
    "VerifyStatus",
    "VersionCopyStatus",
    "VersionLocation",
    "VersionStatus",
    "WasabiCloudStorageAddRequest",
    "WeekDay",
    "Workload",
    "WorkloadCategory",
    "WorkloadStatType",
    "WorkloadStatus",
    "WorkloadTypeStat",
    "WorkloadUsageSummary",
    "WorkloadVersion",
]
